import {
  faMoneyBillWave,
  faGift,
  faChartLine,
  faPiggyBank,
  faHandHoldingDollar,
  faLaptop,
  faCirclePlus,
  faCircleMinus,
  faUtensils,
  faMugHot,
  faBurger,
  faPizzaSlice,
  faCar,
  faGasPump,
  faMotorcycle,
  faBus,
  faTrain,
  faPlaneDeparture,
  faCartShopping,
  faBagShopping,
  faShirt,
  faBolt,
  faDroplet,
  faWifi,
  faMobileScreen,
  faFilm,
  faGamepad,
  faMusic,
  faBriefcaseMedical,
  faPills,
  faGraduationCap,
  faBook,
  faHouse,
  faPaw,
  faDumbbell,
  faBaby,
  faTag,
  faWallet,
  faCreditCard,
  faReceipt,
  faTshirt,
  faTree,
  faGlassMartiniAlt,
  faCoffee,
} from '@fortawesome/free-solid-svg-icons';

// Peta dari nama string (disimpan di database, misal "fa-utensils") ke objek ikon FontAwesome
export const ICON_MAP = {
  'fa-money-bill-wave': faMoneyBillWave,
  'fa-gift': faGift,
  'fa-chart-line': faChartLine,
  'fa-piggy-bank': faPiggyBank,
  'fa-hand-holding-dollar': faHandHoldingDollar,
  'fa-laptop': faLaptop,
  'fa-circle-plus': faCirclePlus,
  'fa-circle-minus': faCircleMinus,
  'fa-utensils': faUtensils,
  'fa-mug-hot': faMugHot,
  'fa-burger': faBurger,
  'fa-pizza-slice': faPizzaSlice,
  'fa-car': faCar,
  'fa-gas-pump': faGasPump,
  'fa-motorcycle': faMotorcycle,
  'fa-bus': faBus,
  'fa-train': faTrain,
  'fa-plane-departure': faPlaneDeparture,
  'fa-cart-shopping': faCartShopping,
  'fa-bag-shopping': faBagShopping,
  'fa-shirt': faShirt,
  'fa-bolt': faBolt,
  'fa-droplet': faDroplet,
  'fa-wifi': faWifi,
  'fa-mobile-screen': faMobileScreen,
  'fa-film': faFilm,
  'fa-gamepad': faGamepad,
  'fa-music': faMusic,
  'fa-briefcase-medical': faBriefcaseMedical,
  'fa-pills': faPills,
  'fa-graduation-cap': faGraduationCap,
  'fa-book': faBook,
  'fa-house': faHouse,
  'fa-paw': faPaw,
  'fa-dumbbell': faDumbbell,
  'fa-baby': faBaby,
  'fa-tag': faTag,
  'fa-wallet': faWallet,
  'fa-credit-card': faCreditCard,
  'fa-receipt': faReceipt,
  'fa-tshirt': faTshirt,
  'fa-tree': faTree,
  'fa-glass-martini-alt': faGlassMartiniAlt,
  'fa-coffee': faCoffee,
};

// Dipakai untuk menampilkan icon; fallback ke fa-tag kalau nama tidak dikenali
export function getIcon(name) {
  return ICON_MAP[name] || faTag;
}

// Daftar kurasi untuk IconPicker, dikelompokkan per kategori penggunaan
export const ICON_GROUPS = [
  {
    label: 'Uang & Keuangan',
    icons: ['fa-money-bill-wave', 'fa-wallet', 'fa-piggy-bank', 'fa-hand-holding-dollar', 'fa-chart-line', 'fa-credit-card', 'fa-receipt', 'fa-gift'],
  },
  {
    label: 'Makanan & Minuman',
    icons: ['fa-utensils', 'fa-mug-hot', 'fa-coffee', 'fa-burger', 'fa-pizza-slice', 'fa-glass-martini-alt'],
  },
  {
    label: 'Transportasi',
    icons: ['fa-car', 'fa-motorcycle', 'fa-gas-pump', 'fa-bus', 'fa-train', 'fa-plane-departure'],
  },
  {
    label: 'Belanja & Gaya Hidup',
    icons: ['fa-cart-shopping', 'fa-bag-shopping', 'fa-shirt', 'fa-tshirt', 'fa-mobile-screen'],
  },
  {
    label: 'Tagihan & Rumah',
    icons: ['fa-bolt', 'fa-droplet', 'fa-wifi', 'fa-house', 'fa-tree'],
  },
  {
    label: 'Hiburan & Gaya Hidup',
    icons: ['fa-film', 'fa-gamepad', 'fa-music', 'fa-dumbbell', 'fa-paw', 'fa-baby'],
  },
  {
    label: 'Kesehatan & Pendidikan',
    icons: ['fa-briefcase-medical', 'fa-pills', 'fa-graduation-cap', 'fa-book'],
  },
  {
    label: 'Lainnya',
    icons: ['fa-laptop', 'fa-circle-plus', 'fa-circle-minus', 'fa-tag'],
  },
];
